events {
    worker_connections  1024;
}

# Le serveur Nginx écoute sur le port 80 et redirige les requêtes vers l'application web qui tourne sur le 9999
http {
   server{
        listen 80;
        
        location / {
            proxy_pass  http://app:9999;     
        }
    }
}